version: "2.4"

services:
  postgres:
    image: postgres:13.2-alpine
    container_name: prisma-database
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRESQL_FSYNC=off
    ports:
      - 25432:5432
    volumes:
      - ./.data/pg/:/var/lib/postgresql/data
      - ./.db/init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  # prisma-postgres-api:
  #   stdin_open: true
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: prisma-postgres-api
  #   depends_on:
  #     - postgres
  #   platform: "linux/amd64"
  #   ports:
  #     - "3000:3000"
  #   restart: always

volumes:
  postgres-data:
  pgadmin-data: